[package]
name = "rust_reader"
version = "0.1.0"
edition = "2024"


[dependencies]
btleplug = "0.11.8"
chrono = "0.4.41"
futures = "0.3.31"
tokio = { version = "1", features = ["full"] }
uuid = "1.17.0"
